### ISSUE TITLE
Navigator Share

### ISSUE THREAD

**Issue by yasir-rafiq** [w3c/web-share#144]
Hi, I am facing problem

-1 Navigator.share always open instagram messenger when I select instagram application. I am looking to do post on instagram not messenger.

-2 Navigor.share open modal to select application for sharing on iphone but instagram is missing there.

can you help.

**Comment by mgiuca** [comment]
Hi @yasir-rafiq 

Both of these problems sound like a problem with Instagram, not the share interface.

It's likely that Instagram Messenger is a share target but Instagram is not, that's why you see Messenger, and on your iPhone you see nothing.

This is not something we can deal with in the web spec side. Closing.

**Comment by yasir-rafiq** [comment]
@mgiuca 
First problem is when I send the file the interaction modal in not open in ios devices. The modal from where I select app. Instagram issue comes later.

Some thing working fine on android devices.

Regards

**Comment by mgiuca** [comment]
It sounds like an implementation issue on iOS. Please contact the web browser team if you still have a problem. (This issue tracker is for the W3C spec.)

**Comment by yasir-rafiq** [comment]
@mgiuca can you share address where I can contact with them?

**Comment by mgiuca** [comment]
Sorry, I'm not affiliated with Apple.

**Comment by marcoscaceres** [comment]
@yasir-rafiq you might try here: https://webkit.org/reporting-bugs/
