### ISSUE TITLE
Should we make share title mandatory?

### ISSUE THREAD

**Issue by AshleyScirra** [w3c/web-share#167]
According to https://bugs.chromium.org/p/chromium/issues/detail?id=1097563#c14, it sounds like the title property is mandatory specifically in Microsoft Edge (Chromium) on Windows 10. This is different to other existing implementations where it is optional.

If most platforms accept it as optional but one platform requires it, that creates an incompatibility where pages that share without a title seem to work most of the time, but are actually broken in Edge. To avoid this perhaps the spec should make the title mandatory to be compatible with Edge on Windows 10.

**Comment by saschanaz** [comment]
Note that [the Firefox implementation](https://searchfox.org/mozilla-central/rev/1b95a0179507a4dc7d4b0c94c2df420dc1a72885/widget/windows/WindowsUIUtils.cpp#363-370) passes \u0020 as the comment says to workaround the OS requirement.

**Comment by AshleyScirra** [comment]
It sounds like a misunderstanding in a follow-up comment: https://bugs.chromium.org/p/chromium/issues/detail?id=1097563#c16

Seems adding a space for the title is the de-facto way around this. Does the spec need to reflect that at all?

**Comment by marcoscaceres** [comment]
Us (Mozilla) adding a \u0020 to work around this is not amazing... but then again, it's OS specific. Another option is talking to the Microsoft folks to see if they can not make it mandatory? I can also see a strong argument for making it mandatory tho.

**Comment by marcoscaceres** [comment]
Ok, I see the discussion is happening in the Chrome bug... looking forward to hearing what the best outcome is there.

**Comment by saschanaz** [comment]
Edge team is fixing their bug, so I guess no intent to change the spec? I think title-less sharing has a valid use case, for example, sharing a tweet or Facebook post shouldn't set a title.

**Comment by marcoscaceres** [comment]
Yeah, I agree @saschanaz... I imagine @mgiuca and @ericwilligers have given this a lot of though too. Looking forward to hearing their thoughts on this.

**Comment by ewilligers** [comment]
We don't want to make title mandatory.

> Seems adding a space for the title is the de-facto way around this. Does the spec need to reflect that at all?

That would be an OS-specific implementation hint. It would be useful information for anybody building a Windows browser from scratch, but I don't know the best place to put it.

**Comment by mgiuca** [comment]
To add context on why we don't want title to be mandatory: sharing systems are typically used to transport arbitrary text strings, URLs or images around. For example, a camera app may take a photograph and have a "share" button to immediately share that image into a chat app -- there would be no appropriate title to add to that photo, unless the camera app added something fairly arbitrary like "Photo taken January 23, 2020", which would then typically show up in the shared chat message, and the user would most likely just want to delete it before sending.

Similarly, you might "share" a web page from a browser, expecting just the URL to be copied over into the target app.

Forcing apps to supply a title essentially pushes the problem that Edge is currently facing (having to come up with a non-empty string) down to each individual app. I don't really understand _why_ Windows requires a title, because as I enumerated above, there are lots of situations where you don't have one. So ideally Windows would be changed to not require a title. Failing that, I think we should continue to have UA-specific hacks to supply a `" "` to Windows (or some other generic string, like "Shared text", "Shared URL" or "Shared image" depending on the other data).

I am happy to have an info box in the spec explaining this Windows quirk.

**Comment by marcoscaceres** [comment]
> I am happy to have an info box in the spec explaining this Windows quirk.

I don't think it's worth adding an info, tbh. The Windows folks are aware of the issue, and everyone implementing on windows already knows about this. And it doesn't directly affect web developers in a meaningful way that would warrant documenting.

**Comment by AshleyScirra** [comment]
FWIW, the comment https://bugs.chromium.org/p/chromium/issues/detail?id=1097563#c13 makes it sound like a change to Windows is unlikely:

> (...it would be hard for Windows OS API to change it.)

I wonder why Windows went with making it mandatory, as explained it seems there are clear use cases where you don't have a title.

**Comment by marcoscaceres** [comment]
unfortunately, I don't think the people that an answer that are here @AshleyScirra :( It might have been just lack of foresight about the use cases, or maybe it's a requirement of the shore modal... but could really be any arbitrary reason.

**Comment by ewilligers** [comment]
Closing this with no change - we have consensus that browsers will not require web developers to supply a share title.
