### ISSUE TITLE
No explicit acknowledgements?

### ISSUE THREAD

**Issue by chaals** [w3c/web-share#265]
Looking through this repo makes it seem like the acknowledgements for this spec are rather miserly, ignoring groups of people like PING as if they made no contribution. That might be common practice in the Web Apps group now (there are different practices across different groups and across time), but it seems unnecessarily exclusive.

🤷

**Comment by marcoscaceres** [comment]
Yeah, we’ve not done a great job at keeping the Acknowledgments up to date… but not because we don’t wholeheartedly appreciate the input from all the horizontal groups (i.e., not exclusive). On the contrary, the spec has been immensely improved because of all the input from a range of folks. 

Typically, we value brevity, but given there’s an Acknowledgment section already, can definitely add something.

**Comment by marcoscaceres** [comment]
Hi @chaals, can you also please check https://github.com/w3c/web-share/pull/269 ? Please feel free to suggest additional text if needed.
